#!/bin/bash

echo "==========================="
echo "add a file to the trash can"
echo "==========================="
echo "current state of the trash can"
./trash -l
touch test_file
./trash test_file
echo "new state of the trash can"
./trash -l
echo "remove the file from the trash can"
./trash -d test_file
echo "new state of the trash can"
./trash -l


echo "==========================="
echo "add a folder to the trash can"
echo "==========================="
echo "current state of the trash can"
./trash -l
mkdir test_folder
touch test_folder/aa
./trash test_folder/
echo "new state of the trash can"
./trash -l
echo "remove the folder from the trash can"
./trash -d test_folder/
echo "new state of the trash can"
./trash -l


echo "==========================="
echo "add a file to the trash can and recover it"
echo "==========================="
echo "current state of the trash can"
./trash -l
touch test_recover
./trash test_recover
echo "new state of the trash can"
./trash -l
echo "recover the file from the trash can"
./trash -r test_recover
echo "new state of the trash can"
./trash -l
